# Generated by Django 3.0.5 on 2020-05-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200514_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_student_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='course',
            name='student_count',
            field=models.IntegerField(default=0),
        ),
    ]
