# Generated by Django 3.0.5 on 2020-05-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200523_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenroll',
            unique_together={('student', 'course')},
        ),
    ]
