version: '3'

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./student_app:/student_app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
